### PR TITLE
Build variants

### PR DESCRIPTION
**Pull request by wagnerb4**
refer to https://github.com/kaczmarkiewiczp/rcloneExplorer/pull/218

### CODE REVIEW

**Comment by x0b** [comment]
> Is there a chance that this will be merged any time soon, because I would really like to have this App in the F-Droid store?

I would also like to have the app on F-Droid. However, my fork neither on a technical nor on a legal perspective compatible with that PR.

Would you be willing to prepare a new PR? I currently lack the time for major changes, so F-Droid is really far down on the roadmap.

**Comment by wagnerb4** [comment]
> > Is there a chance that this will be merged any time soon, because I would really like to have this App in the F-Droid store?
> 
> I would also like to have the app on F-Droid. However, my fork is neither on a technical nor on a legal perspective compatible with that PR.
> 
> Would you be willing to prepare a new PR? I currently lack the time for major changes, so F-Droid is really far down on the roadmap.

I currently don't have much time either. When I have some time I'll prepare the PR, but I am not promising anything.

**Comment by x0b** [comment]
I actually think it would be much easier to place this on a "pure oss" branch with firebase integration removed - which could cut down massively on the code duplication in this PR. Also, I already replaced Firebase Notifications with a GitHub API call, but we would need to make the update checks opt-in by default to comply with F-Droid policy.

Also, since F-Droid does not support build secrets we can't work around hostile providers (like [Yandex](https://forum.rclone.org/t/yandexdisk-problem/14478/17)) with our own OAuth secrets -  so the F-Droid would definitely be a "lite" version.

**Comment by x0b** [comment]
Update: I've added a [oss branch](https://github.com/x0b/rcx/tree/oss) with firebase/gms removed. This should be ready for RFP now.

**Comment by x0b** [comment]
I'm going to close this now since the changes proposed here have been included and an RFP is in progress.

**Pull request closed without merging**
